### ISSUE TITLE
Show min/max publish rate of events and telemetries in PDF

### ISSUE THREAD

**Issue by tnakamot** [tmtsoftware/icd#44]
The ICD document in PDF generated by icd-db command does not include the min/max publish rate of events and telemetries. The generated PDF should include it.

For example, this model file in TCS define imgAtmDispersion event with min/max rate = 1 Hz.
https://github.com/tmt-icd/TCS-Model-Files/blob/master/iris/publish-model.conf

However, the PDF generated from this model file does not show that information, but only required rate defined in the IRIS model files (actually not defined for most of the events/telemetries, so shown as "0.0 Hz").
https://docushare.tmt.org/docushare/dsweb/Get/Version-78109/IRIS-TCS_1p1_Final.pdf

**Comment by kgillies** [comment]
As you point out the PDF file does not show the max and min rate of the publisher of an event in the subscriber data in the ICD. It only shows the requiredRate specified in the subscribe model file. I think it is a good idea to show this so that it is clear that a requiredRate is within the max rate of the pbulisher, but it's a new feature that we will have to add.

**Comment by abrighton** [comment]
Min and max rate are now displayed, if defined.
